### ISSUE TITLE
I wanna add support to Tiger Lake

### ISSUE THREAD

**Issue by macsupermac** [ChefKissInc/NootedBlue#10] opened 2023-08-23 04:30 UTC
As we know,Apple has given up the support for Tiger Lake,but Iris Xe Graphics is powerful,I hope NootInc can support Tiger Lake.You have already developed the drivers for AMD Vega Graphics.Thank you for your efforts!!!

**Comment by notluke27** [comment] 2023-08-23 21:29
Same. I have a 12th gen core i5 laptop (alder lake) with iris xe.

**Comment by Zormeister** [comment] 2023-09-28 13:13
Duplicate of #6.

**Closed by Zormeister** 2023-09-28 13:13 UTC
